2013/06/26 18:08:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/index.php?r=site/login
---
2013/06/26 18:08:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/index.php?r=site/login
---
2013/06/26 18:08:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/
---
2013/06/26 18:08:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/index.php
---
2013/06/26 18:08:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/
---
2013/06/26 18:08:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/index.php
---
2013/06/26 18:11:15 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "index".' in F:\MyWebSite\yii-web3s\framework\web\CController.php:878
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#1 F:\MyWebSite\yii-web3s\protected\controllers\frontend\SiteController.php(32): CController->render('index')
#2 F:\MyWebSite\yii-web3s\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 F:\MyWebSite\yii-web3s\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 F:\MyWebSite\yii-web3s\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 F:\MyWebSite\yii-web3s\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(282): CController->run('')
#7 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#10 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#11 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#12 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#13 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#14 {main}
REQUEST_URI=/index.php?r=site/login
---
2013/06/26 18:11:39 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "index".' in F:\MyWebSite\yii-web3s\framework\web\CController.php:878
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#1 F:\MyWebSite\yii-web3s\protected\controllers\frontend\SiteController.php(32): CController->render('index')
#2 F:\MyWebSite\yii-web3s\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 F:\MyWebSite\yii-web3s\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 F:\MyWebSite\yii-web3s\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 F:\MyWebSite\yii-web3s\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(282): CController->run('')
#7 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#10 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#11 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#12 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#13 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#14 {main}
REQUEST_URI=/index.php?r=site/login
---
2013/06/26 18:11:41 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "index".' in F:\MyWebSite\yii-web3s\framework\web\CController.php:878
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#1 F:\MyWebSite\yii-web3s\protected\controllers\frontend\SiteController.php(32): CController->render('index')
#2 F:\MyWebSite\yii-web3s\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 F:\MyWebSite\yii-web3s\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 F:\MyWebSite\yii-web3s\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 F:\MyWebSite\yii-web3s\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(282): CController->run('')
#7 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#10 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#11 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#12 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#13 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#14 {main}
REQUEST_URI=/index.php?r=site/login
---
2013/06/26 18:14:10 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "index".' in F:\MyWebSite\yii-web3s\framework\web\CController.php:878
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#1 F:\MyWebSite\yii-web3s\protected\controllers\frontend\SiteController.php(32): CController->render('index')
#2 F:\MyWebSite\yii-web3s\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 F:\MyWebSite\yii-web3s\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 F:\MyWebSite\yii-web3s\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 F:\MyWebSite\yii-web3s\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(282): CController->run('')
#7 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#10 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#11 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#12 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#13 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#14 {main}
REQUEST_URI=/index.php?r=test
---
2013/06/26 18:14:14 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "index".' in F:\MyWebSite\yii-web3s\framework\web\CController.php:878
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#1 F:\MyWebSite\yii-web3s\protected\controllers\frontend\SiteController.php(32): CController->render('index')
#2 F:\MyWebSite\yii-web3s\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 F:\MyWebSite\yii-web3s\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 F:\MyWebSite\yii-web3s\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 F:\MyWebSite\yii-web3s\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(282): CController->run('')
#7 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#10 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#11 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#12 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#13 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#14 {main}
REQUEST_URI=/index.php?r=test/test
---
2013/06/26 18:16:56 [error] [exception.CException] exception 'CException' with message 'Property "SiteController.breadcrumbs" is not defined.' in F:\MyWebSite\yii-web3s\framework\base\CComponent.php:173
Stack trace:
#0 F:\MyWebSite\yii-web3s\protected\views\frontend\site\pages\about.php(5): CComponent->__set('breadcrumbs', Array)
#1 F:\MyWebSite\yii-web3s\framework\web\CBaseController.php(126): require('F:\MyWebSite\yi...')
#2 F:\MyWebSite\yii-web3s\framework\web\CBaseController.php(95): CBaseController->renderInternal('F:\MyWebSite\yi...', NULL, true)
#3 F:\MyWebSite\yii-web3s\framework\web\CController.php(869): CBaseController->renderFile('F:\MyWebSite\yi...', NULL, true)
#4 F:\MyWebSite\yii-web3s\framework\web\CController.php(782): CController->renderPartial('pages/about', NULL, true)
#5 F:\MyWebSite\yii-web3s\framework\web\actions\CViewAction.php(140): CController->render('pages/about')
#6 F:\MyWebSite\yii-web3s\framework\web\actions\CAction.php(76): CViewAction->run()
#7 F:\MyWebSite\yii-web3s\framework\web\CController.php(308): CAction->runWithParams(Array)
#8 F:\MyWebSite\yii-web3s\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#9 F:\MyWebSite\yii-web3s\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#10 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(282): CController->run('page')
#11 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#12 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#13 F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#14 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#15 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#16 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#17 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#18 {main}
REQUEST_URI=/index.php/site/page?view=about
---
2013/06/26 18:17:00 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (F:\MyWebSite\yii-web3s\framework\YiiBase.php:421)
Stack trace:
#0 F:\MyWebSite\yii-web3s\protected\controllers\frontend\SiteController.php(80): spl_autoload_call()
#1 F:\MyWebSite\yii-web3s\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#2 F:\MyWebSite\yii-web3s\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 F:\MyWebSite\yii-web3s\framework\web\CController.php(286): SiteController->runAction()
#4 F:\MyWebSite\yii-web3s\framework\web\CController.php(265): SiteController->runActionWithFilters()
#5 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(282): SiteController->run()
#6 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php(30): CWebApplication->run()
#9 unknown(0): WebApplicationEndBehavior->runEnd()
#10 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array()
#11 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->__call()
#12 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd()
REQUEST_URI=/index.php/site/login
in F:\MyWebSite\yii-web3s\protected\controllers\frontend\SiteController.php (80)
in F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php (30)
in F:\MyWebSite\yii-web3s\public\index.php (13)
2013/06/26 18:17:28 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (F:\MyWebSite\yii-web3s\framework\YiiBase.php:421)
Stack trace:
#0 F:\MyWebSite\yii-web3s\protected\controllers\frontend\SiteController.php(80): spl_autoload_call()
#1 F:\MyWebSite\yii-web3s\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#2 F:\MyWebSite\yii-web3s\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 F:\MyWebSite\yii-web3s\framework\web\CController.php(286): SiteController->runAction()
#4 F:\MyWebSite\yii-web3s\framework\web\CController.php(265): SiteController->runActionWithFilters()
#5 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(282): SiteController->run()
#6 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php(30): CWebApplication->run()
#9 unknown(0): WebApplicationEndBehavior->runEnd()
#10 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array()
#11 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->__call()
#12 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd()
REQUEST_URI=/index.php/site/login
in F:\MyWebSite\yii-web3s\protected\controllers\frontend\SiteController.php (80)
in F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php (30)
in F:\MyWebSite\yii-web3s\public\index.php (13)
2013/06/26 18:18:23 [error] [exception.CException] exception 'CException' with message 'Property "SiteController.breadcrumbs" is not defined.' in F:\MyWebSite\yii-web3s\framework\base\CComponent.php:173
Stack trace:
#0 F:\MyWebSite\yii-web3s\protected\views\frontend\site\login.php(7): CComponent->__set('breadcrumbs', Array)
#1 F:\MyWebSite\yii-web3s\framework\web\CBaseController.php(126): require('F:\MyWebSite\yi...')
#2 F:\MyWebSite\yii-web3s\framework\web\CBaseController.php(95): CBaseController->renderInternal('F:\MyWebSite\yi...', Array, true)
#3 F:\MyWebSite\yii-web3s\framework\web\CController.php(869): CBaseController->renderFile('F:\MyWebSite\yi...', Array, true)
#4 F:\MyWebSite\yii-web3s\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#5 F:\MyWebSite\yii-web3s\protected\controllers\frontend\SiteController.php(98): CController->render('login', Array)
#6 F:\MyWebSite\yii-web3s\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 F:\MyWebSite\yii-web3s\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 F:\MyWebSite\yii-web3s\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 F:\MyWebSite\yii-web3s\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(282): CController->run('login')
#11 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#13 F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#14 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#15 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#16 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#17 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#18 {main}
REQUEST_URI=/index.php/site/login
---
2013/06/26 18:18:24 [error] [exception.CException] exception 'CException' with message 'Property "SiteController.breadcrumbs" is not defined.' in F:\MyWebSite\yii-web3s\framework\base\CComponent.php:173
Stack trace:
#0 F:\MyWebSite\yii-web3s\protected\views\frontend\site\login.php(7): CComponent->__set('breadcrumbs', Array)
#1 F:\MyWebSite\yii-web3s\framework\web\CBaseController.php(126): require('F:\MyWebSite\yi...')
#2 F:\MyWebSite\yii-web3s\framework\web\CBaseController.php(95): CBaseController->renderInternal('F:\MyWebSite\yi...', Array, true)
#3 F:\MyWebSite\yii-web3s\framework\web\CController.php(869): CBaseController->renderFile('F:\MyWebSite\yi...', Array, true)
#4 F:\MyWebSite\yii-web3s\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#5 F:\MyWebSite\yii-web3s\protected\controllers\frontend\SiteController.php(98): CController->render('login', Array)
#6 F:\MyWebSite\yii-web3s\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 F:\MyWebSite\yii-web3s\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 F:\MyWebSite\yii-web3s\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 F:\MyWebSite\yii-web3s\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(282): CController->run('login')
#11 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#13 F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#14 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#15 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#16 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#17 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#18 {main}
REQUEST_URI=/index.php/site/login
---
2013/06/26 18:18:42 [error] [exception.CException] exception 'CException' with message 'Property "SiteController.breadcrumbs" is not defined.' in F:\MyWebSite\yii-web3s\framework\base\CComponent.php:173
Stack trace:
#0 F:\MyWebSite\yii-web3s\protected\views\frontend\site\contact.php(7): CComponent->__set('breadcrumbs', Array)
#1 F:\MyWebSite\yii-web3s\framework\web\CBaseController.php(126): require('F:\MyWebSite\yi...')
#2 F:\MyWebSite\yii-web3s\framework\web\CBaseController.php(95): CBaseController->renderInternal('F:\MyWebSite\yi...', Array, true)
#3 F:\MyWebSite\yii-web3s\framework\web\CController.php(869): CBaseController->renderFile('F:\MyWebSite\yi...', Array, true)
#4 F:\MyWebSite\yii-web3s\framework\web\CController.php(782): CController->renderPartial('contact', Array, true)
#5 F:\MyWebSite\yii-web3s\protected\controllers\frontend\SiteController.php(72): CController->render('contact', Array)
#6 F:\MyWebSite\yii-web3s\framework\web\actions\CInlineAction.php(49): SiteController->actionContact()
#7 F:\MyWebSite\yii-web3s\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 F:\MyWebSite\yii-web3s\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 F:\MyWebSite\yii-web3s\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(282): CController->run('contact')
#11 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('site/contact')
#12 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#13 F:\MyWebSite\yii-web3s\protected\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#14 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#15 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#16 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#17 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#18 {main}
REQUEST_URI=/index.php/site/contact
HTTP_REFERER=http://yii-web3s.local/index.php?r=site/login
---
2013/06/27 17:22:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/index.php/gii
---
2013/06/29 10:26:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/06/29 10:26:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/06/29 10:27:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "index" was not found.' in F:\MyWebSite\yii-web3s\framework\web\actions\CViewAction.php:112
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('index')
#1 F:\MyWebSite\yii-web3s\framework\web\actions\CAction.php(76): CViewAction->run()
#2 F:\MyWebSite\yii-web3s\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 F:\MyWebSite\yii-web3s\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 F:\MyWebSite\yii-web3s\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(282): CController->run('page')
#6 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page/about')
#7 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#9 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#10 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#11 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#12 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#13 {main}
REQUEST_URI=/index.php/site/page/about
---
2013/07/01 16:22:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "backend".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('backend')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/backend
---
2013/07/01 16:22:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/06 12:50:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/08 15:47:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/18 17:05:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/21 16:13:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:04:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "posts".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/
---
2013/07/28 06:04:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "posts".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/
---
2013/07/28 06:05:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "posts".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/
---
2013/07/28 06:05:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:05:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:05:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:05:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:05:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:05:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:05:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "posts".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/
---
2013/07/28 06:05:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "posts".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/
---
2013/07/28 06:05:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:05:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:05:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:05:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:05:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:05:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:05:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:05:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:05:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:06:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:06:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:06:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:06:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:23:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "posts".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/
---
2013/07/28 06:23:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:23:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "posts".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/
HTTP_REFERER=http://yii-web3s.local/
---
2013/07/28 06:23:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:23:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "posts".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/
HTTP_REFERER=http://yii-web3s.local/
---
2013/07/28 06:23:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:23:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:23:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:23:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "posts".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/
HTTP_REFERER=http://yii-web3s.local/
---
2013/07/28 06:23:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:23:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:23:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "posts".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/
HTTP_REFERER=http://yii-web3s.local/
---
2013/07/28 06:23:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:23:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:23:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 06:23:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:32:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:32:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:32:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:32:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:32:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:32:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:32:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:32:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:32:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:32:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:32:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:32:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:32:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:32:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:32:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:32:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:32:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:32:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:39:56 [error] [exception.CException] exception 'CException' with message 'The controller path "F:\MyWebSite\yii-web3s\ProtectedShop\frontend\controllers" is not a valid directory.' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:422
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(152): CWebApplication->setControllerPath('F:\MyWebSite\yi...')
#1 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(43): CComponent->__set('controllerPath', 'F:\MyWebSite\yi...')
#2 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(558): WebApplicationEndBehavior->changeModulePaths(Object(CEvent))
#3 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(36): CComponent->raiseEvent('onModuleCreate', Object(CEvent))
#4 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(28): WebApplicationEndBehavior->onModuleCreate(Object(CEvent))
#5 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#6 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#7 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#8 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#9 {main}
REQUEST_URI=/site/index
---
2013/07/28 09:39:57 [error] [exception.CException] exception 'CException' with message 'The controller path "F:\MyWebSite\yii-web3s\ProtectedShop\frontend\controllers" is not a valid directory.' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:422
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(152): CWebApplication->setControllerPath('F:\MyWebSite\yi...')
#1 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(43): CComponent->__set('controllerPath', 'F:\MyWebSite\yi...')
#2 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(558): WebApplicationEndBehavior->changeModulePaths(Object(CEvent))
#3 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(36): CComponent->raiseEvent('onModuleCreate', Object(CEvent))
#4 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(28): WebApplicationEndBehavior->onModuleCreate(Object(CEvent))
#5 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#6 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#7 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#8 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#9 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:41:21 [error] [exception.CException] exception 'CException' with message 'The controller path "F:\MyWebSite\yii-web3s\ProtectedShop\frontend\controllers" is not a valid directory.' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:422
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(152): CWebApplication->setControllerPath('F:\MyWebSite\yi...')
#1 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(43): CComponent->__set('controllerPath', 'F:\MyWebSite\yi...')
#2 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(558): WebApplicationEndBehavior->changeModulePaths(Object(CEvent))
#3 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(36): CComponent->raiseEvent('onModuleCreate', Object(CEvent))
#4 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(28): WebApplicationEndBehavior->onModuleCreate(Object(CEvent))
#5 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#6 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#7 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#8 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#9 {main}
REQUEST_URI=/site/index
---
2013/07/28 09:41:21 [error] [exception.CException] exception 'CException' with message 'The controller path "F:\MyWebSite\yii-web3s\ProtectedShop\frontend\controllers" is not a valid directory.' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:422
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(152): CWebApplication->setControllerPath('F:\MyWebSite\yi...')
#1 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(43): CComponent->__set('controllerPath', 'F:\MyWebSite\yi...')
#2 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(558): WebApplicationEndBehavior->changeModulePaths(Object(CEvent))
#3 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(36): CComponent->raiseEvent('onModuleCreate', Object(CEvent))
#4 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(28): WebApplicationEndBehavior->onModuleCreate(Object(CEvent))
#5 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#6 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#7 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#8 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#9 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:41:26 [error] [exception.CException] exception 'CException' with message 'The controller path "F:\MyWebSite\yii-web3s\ProtectedShop\frontend\controllers" is not a valid directory.' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:422
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(152): CWebApplication->setControllerPath('F:\MyWebSite\yi...')
#1 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(43): CComponent->__set('controllerPath', 'F:\MyWebSite\yi...')
#2 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(558): WebApplicationEndBehavior->changeModulePaths(Object(CEvent))
#3 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(36): CComponent->raiseEvent('onModuleCreate', Object(CEvent))
#4 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(28): WebApplicationEndBehavior->onModuleCreate(Object(CEvent))
#5 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#6 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#7 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#8 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#9 {main}
REQUEST_URI=/
---
2013/07/28 09:41:26 [error] [exception.CException] exception 'CException' with message 'The controller path "F:\MyWebSite\yii-web3s\ProtectedShop\frontend\controllers" is not a valid directory.' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:422
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(152): CWebApplication->setControllerPath('F:\MyWebSite\yi...')
#1 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(43): CComponent->__set('controllerPath', 'F:\MyWebSite\yi...')
#2 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(558): WebApplicationEndBehavior->changeModulePaths(Object(CEvent))
#3 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(36): CComponent->raiseEvent('onModuleCreate', Object(CEvent))
#4 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(28): WebApplicationEndBehavior->onModuleCreate(Object(CEvent))
#5 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#6 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#7 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#8 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#9 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:41:59 [error] [exception.CException] exception 'CException' with message 'The controller path "F:\MyWebSite\yii-web3s\ProtectedShop\frontend\controllers" is not a valid directory.' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:422
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(152): CWebApplication->setControllerPath('F:\MyWebSite\yi...')
#1 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(43): CComponent->__set('controllerPath', 'F:\MyWebSite\yi...')
#2 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(558): WebApplicationEndBehavior->changeModulePaths(Object(CEvent))
#3 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(36): CComponent->raiseEvent('onModuleCreate', Object(CEvent))
#4 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(28): WebApplicationEndBehavior->onModuleCreate(Object(CEvent))
#5 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#6 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#7 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#8 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#9 {main}
REQUEST_URI=/
---
2013/07/28 09:41:59 [error] [exception.CException] exception 'CException' with message 'The controller path "F:\MyWebSite\yii-web3s\ProtectedShop\frontend\controllers" is not a valid directory.' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:422
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(152): CWebApplication->setControllerPath('F:\MyWebSite\yi...')
#1 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(43): CComponent->__set('controllerPath', 'F:\MyWebSite\yi...')
#2 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(558): WebApplicationEndBehavior->changeModulePaths(Object(CEvent))
#3 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(36): CComponent->raiseEvent('onModuleCreate', Object(CEvent))
#4 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(28): WebApplicationEndBehavior->onModuleCreate(Object(CEvent))
#5 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#6 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#7 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#8 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#9 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:42:04 [error] [exception.CException] exception 'CException' with message 'The controller path "F:\MyWebSite\yii-web3s\ProtectedShop\frontend\controllers" is not a valid directory.' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:422
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(152): CWebApplication->setControllerPath('F:\MyWebSite\yi...')
#1 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(43): CComponent->__set('controllerPath', 'F:\MyWebSite\yi...')
#2 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(558): WebApplicationEndBehavior->changeModulePaths(Object(CEvent))
#3 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(36): CComponent->raiseEvent('onModuleCreate', Object(CEvent))
#4 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(28): WebApplicationEndBehavior->onModuleCreate(Object(CEvent))
#5 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#6 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#7 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#8 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#9 {main}
REQUEST_URI=/
---
2013/07/28 09:42:05 [error] [exception.CException] exception 'CException' with message 'The controller path "F:\MyWebSite\yii-web3s\ProtectedShop\frontend\controllers" is not a valid directory.' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:422
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(152): CWebApplication->setControllerPath('F:\MyWebSite\yi...')
#1 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(43): CComponent->__set('controllerPath', 'F:\MyWebSite\yi...')
#2 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(558): WebApplicationEndBehavior->changeModulePaths(Object(CEvent))
#3 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(36): CComponent->raiseEvent('onModuleCreate', Object(CEvent))
#4 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(28): WebApplicationEndBehavior->onModuleCreate(Object(CEvent))
#5 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#6 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#7 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#8 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#9 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:43:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "posts".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/
---
2013/07/28 09:43:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:43:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:43:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 09:47:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 12:55:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 12:55:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 12:55:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 12:55:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 12:55:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 12:55:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 12:55:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 12:55:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 12:55:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 12:55:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 16:49:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 16:49:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 16:49:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 16:49:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 18:35:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 18:35:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 18:35:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/28 18:35:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/29 16:36:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "posts".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/
---
2013/07/29 16:36:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "posts".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/index.php?r=site/login
---
2013/07/29 16:36:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 F:\MyWebSite\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/07/29 18:43:08 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (F:\MyWebSite\yii-web3s\framework\YiiBase.php:421)
Stack trace:
#0 F:\MyWebSite\yii-web3s\ProtectedShop\modules\frontend\controllers\SiteController.php(80): spl_autoload_call()
#1 F:\MyWebSite\yii-web3s\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#2 F:\MyWebSite\yii-web3s\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 F:\MyWebSite\yii-web3s\framework\web\CController.php(286): SiteController->runAction()
#4 F:\MyWebSite\yii-web3s\framework\web\CController.php(265): SiteController->runActionWithFilters()
#5 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(282): SiteController->run()
#6 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CWebApplication->run()
#9 unknown(0): WebApplicationEndBehavior->runEnd()
#10 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array()
#11 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->__call()
#12 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd()
REQUEST_URI=/site/login
in F:\MyWebSite\yii-web3s\ProtectedShop\modules\frontend\controllers\SiteController.php (80)
in F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php (30)
in F:\MyWebSite\yii-web3s\public\index.php (13)
2013/07/29 18:43:11 [error] [php] include(ContactForm.php): failed to open stream: No such file or directory (F:\MyWebSite\yii-web3s\framework\YiiBase.php:421)
Stack trace:
#0 F:\MyWebSite\yii-web3s\ProtectedShop\modules\frontend\controllers\SiteController.php(54): spl_autoload_call()
#1 F:\MyWebSite\yii-web3s\framework\web\actions\CInlineAction.php(49): SiteController->actionContact()
#2 F:\MyWebSite\yii-web3s\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 F:\MyWebSite\yii-web3s\framework\web\CController.php(286): SiteController->runAction()
#4 F:\MyWebSite\yii-web3s\framework\web\CController.php(265): SiteController->runActionWithFilters()
#5 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(282): SiteController->run()
#6 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CWebApplication->run()
#9 unknown(0): WebApplicationEndBehavior->runEnd()
#10 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array()
#11 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->__call()
#12 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd()
REQUEST_URI=/site/contact
in F:\MyWebSite\yii-web3s\ProtectedShop\modules\frontend\controllers\SiteController.php (54)
in F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php (30)
in F:\MyWebSite\yii-web3s\public\index.php (13)
2013/07/29 19:13:41 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (F:\MyWebSite\yii-web3s\framework\YiiBase.php:421)
Stack trace:
#0 F:\MyWebSite\yii-web3s\ProtectedShop\modules\frontend\controllers\SiteController.php(80): spl_autoload_call()
#1 F:\MyWebSite\yii-web3s\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#2 F:\MyWebSite\yii-web3s\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 F:\MyWebSite\yii-web3s\framework\web\CController.php(286): SiteController->runAction()
#4 F:\MyWebSite\yii-web3s\framework\web\CController.php(265): SiteController->runActionWithFilters()
#5 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(282): SiteController->run()
#6 F:\MyWebSite\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 F:\MyWebSite\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CWebApplication->run()
#9 unknown(0): WebApplicationEndBehavior->runEnd()
#10 F:\MyWebSite\yii-web3s\framework\base\CComponent.php(260): call_user_func_array()
#11 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->__call()
#12 F:\MyWebSite\yii-web3s\public\index.php(13): CWebApplication->runEnd()
REQUEST_URI=/site/login
in F:\MyWebSite\yii-web3s\ProtectedShop\modules\frontend\controllers\SiteController.php (80)
in F:\MyWebSite\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php (30)
in F:\MyWebSite\yii-web3s\public\index.php (13)
2013/08/02 06:28:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\MyProject\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\MyProject\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\MyProject\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\MyProject\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 D:\MyProject\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 D:\MyProject\yii-web3s\public\index.php(13): CComponent->__call('runEnd', Array)
#6 D:\MyProject\yii-web3s\public\index.php(13): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/08/05 03:22:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\MyProject\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\MyProject\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\MyProject\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\MyProject\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 D:\MyProject\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 D:\MyProject\yii-web3s\public\index.php(19): CComponent->__call('runEnd', Array)
#6 D:\MyProject\yii-web3s\public\index.php(19): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/favicon.ico
---
2013/08/05 03:22:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin.php".' in D:\MyProject\yii-web3s\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\MyProject\yii-web3s\framework\web\CWebApplication.php(141): CWebApplication->runController('admin.php')
#1 D:\MyProject\yii-web3s\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\MyProject\yii-web3s\ProtectedShop\behaviors\WebApplicationEndBehavior.php(30): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('frontend')
#4 D:\MyProject\yii-web3s\framework\base\CComponent.php(260): call_user_func_array(Array, Array)
#5 D:\MyProject\yii-web3s\public\index.php(19): CComponent->__call('runEnd', Array)
#6 D:\MyProject\yii-web3s\public\index.php(19): CWebApplication->runEnd('frontend')
#7 {main}
REQUEST_URI=/admin.php
---
